test_suites:
    - name: lint
      script_path: /root/okta/okta-signin-widget/scripts
      sort_order: '1'
      timeout: '10'
      script_name: lint
      criteria: MERGE
      queue_name: small
    - name: unit-karma
      script_path: /root/okta/okta-signin-widget/scripts
      sort_order: '2'
      timeout: '15'
      script_name: unit-karma
      criteria: MERGE
      queue_name: small
    - name: unit-jest
      script_path: /root/okta/okta-signin-widget/scripts
      sort_order: '3'
      timeout: '15'
      script_name: unit-jest
      criteria: MERGE
      queue_name: small
    - name: testcafe
      script_path: /root/okta/okta-signin-widget/scripts
      sort_order: '4'
      timeout: '30'
      script_name: testcafe
      criteria: MERGE
      queue_name: small
    - name: detect-english-leaks
      script_path: /root/okta/okta-signin-widget/scripts
      sort_order: '8'
      timeout: '20'
      script_name: detect-english-leaks
      criteria: MERGE
      queue_name: small
    - name: e2e
      script_path: /root/okta/okta-signin-widget/scripts
      sort_order: '5'
      timeout: '20'
      script_name: e2e
      criteria: MERGE
      queue_name: small
    - name: publish
      script_path: /root/okta/okta-signin-widget/scripts
      sort_order: '7'
      timeout: '10'
      script_name: publish
      criteria: MERGE
      queue_name: small
    - name: tsd
      script_path: /root/okta/okta-signin-widget/scripts
      sort_order: '9'
      timeout: '15'
      script_name: tsd
      criteria: MERGE
      queue_name: small
